import { Noto_Sans_KR, Roboto as RobotoFont } from 'next/font/google';
import './styles/reset.css';
import './styles/theme.css';
import * as globalStyles from "./styles/global.css";
import Lnb from './components/Lnb';
import Header from './components/Header';

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const NotoSansKR = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400','500','600','700'],
  variable: '--font-noto-sans-kr'
});

const Roboto = RobotoFont({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }){
  return (
    <html lang="kr">
      <body className={notoSansKR.className}>
        <div className={globalStyles.wrapper}>
          <Lnb />
          <div className={globalStyles.wrap}>
            <Header />
            <div className={globalStyles.container}>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
