import { ReactNode } from 'react';
import type { Metadata } from "next";
import { Noto_Sans_KR, Roboto } from 'next/font/google';
import './styles/reset.css';
import './styles/global.css';
import './styles/theme.css';
import { wrapper, wrap, container } from './styles/global.css';
import Lnb from './components/Lnb';
import Header from './components/Header';

import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const notoSansKR = Noto_Sans_KR({
  subsets: ['latin'],
  weight: ['400','500','600','700'],
  variable: '--font-noto-sans-kr'
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
  variable: '--font-roboto'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="kr">
      <body className={notoSansKR.className}>
        <div className={wrapper}>
          <Lnb />
          <div className={wrap}>
            <Header />
            <div className={container}>
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
